### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTitle' of undefined

### ISSUE THREAD

**Issue by pitosalas** [nobuhito/atom-export-html#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.3
**System**: Mac OS X 10.11.2
**Thrown From**: [export-html](https://github.com/nobuhito/atom-export-html) package, v0.9.1
### Stack Trace

Uncaught TypeError: Cannot read property 'getTitle' of undefined

```
At /Users/pitosalas/.atom/packages/export-html/lib/export-html.coffee:38

TypeError: Cannot read property 'getTitle' of undefined
    at Object.module.exports.ExportHtml.export [as export] (/Users/pitosalas/.atom/packages/export-html/lib/export-html.coffee:38:22)
    at atom-workspace.subscriptions.add.atom.commands.add.export-html:export (/Users/pitosalas/.atom/packages/export-html/lib/export-html.coffee:30:85)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:987:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -3:54.1.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-atom-light-syntax.theme-atom-light-ui)
     -2:49.3.0 markdown-preview:toggle (atom-text-editor.editor.is-focused)
     -2:35.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:35.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -2:15.3.0 core:close (div.release-notes.padded.pane-item.native-key-bindings)
     -2:02.9.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -1:36.5.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:02.3.0 export-html:export (div.markdown-preview.native-key-bindings)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ],
    "disabledPackages": [
      "ruby-bundler",
      "ruby-bundler",
      "language-coffee-script",
      "language-objective-c",
      "language-java",
      "language-go",
      "language-csharp",
      "language-clojure",
      "language-c",
      "language-less",
      "language-make",
      "language-mustache",
      "language-perl",
      "language-php",
      "language-python",
      "language-sass",
      "language-source",
      "language-toml",
      "language-xml",
      "metrics",
      "spell-check"
    ],
    "projectHome": "/mydev"
  }
}
```
### Installed Packages

``` coffee
# User
.bin, vundefined
atom-typescript, v7.11.1
autocomplete-ruby, v0.1.0
export-html, v0.9.1
linter, v1.11.2
linter-javac, v1.3.0
linter-rubocop, v0.4.4
node-debugger, v1.1.9
project-manager, v2.6.5
ruby-block, v0.3.5

# Dev
No dev packages
```

**Comment by kohenkatz** [comment]
I don't know what the original steps to cause this were, but here's how I got it:
1. Right-click a directory in the tree and choose "Search in directory"
2. Search for something
3. Try to run "Export HTML" on the Search results tab.
